services:
  - type: web
    name: flag-quiz
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flag-quiz-db
          property: connectionString

databases:
  - name: flag-quiz-db
    ipAllowList: []